### ISSUE TITLE
ACE accounts must set up oauth keys server-side

### ISSUE THREAD

**Issue by danepowell** [jenter/decoupled-drupal#16]
Currently, if you install the site on ACE, you'll get errors related to permissions on the snakeoil oauth keys.

The problem is that the ACE filesystem is read only and deployed via Git. Git only stores the execute bit on files, so there's no way to set the correct permissions on the snakeoil key files.

That's okay though, because you shouldn't be using the snakoil keys on ACE anyway. You should generate secure keys and store them server-side, and bring them in with config split. We should document this process somehow.

Unfortunately this will fail for CDEs, Pipelines, and other environements where you can't install keys server side first.

**Comment by gnarf** [comment]
Whatever the process ends up being, we should try to make it as easy as possible since this is a "tutorial" repository.

**Comment by jenter** [comment]
@danepowell is this still outstanding?

**Comment by danepowell** [comment]
Yes we still need to resolve this, because the OAuth keys cause problems both for fresh checkouts and deploys to ACE.

It doesn't completely break the site, but it's more or less unusable for content editing because every page is filled with notices about the incorrect permissions. To resolve this, someone has to change permissions on the keys locally after checking out the repo, or install the keys server side.

I think we have a few options. The decision probably comes down to whether we want to include Simple OAuth in the tutorial:
# I've opened an upstream issue for Lightning (https://github.com/acquia/lightning/issues/511) to split out the SimpleOAuth functionality so we can simply disable it and make all of this go away. I can work on a patch for that.
# We can simply hack the Simple OAuth module to disable these permissions checks (probably easiest, but also a little dangerous in case someone takes our example to production).
# Update documentation to tell people how to install keys and set permissions on them. This isn't super hard, but I also think it's a little beyond the scope of the tutorial.

**Comment by jenter** [comment]
@danepowell I think OAuth is not a requirement and really a 'nice to have', so I think it makes sense to remove.

**Comment by danepowell** [comment]
I just realized we can probably just delete the keys and OAuth configuration altogether if we aren't using it. That wasn't an option back when we first set up the project, but I think it should work now. I'll test.
