### ISSUE TITLE
Consistency of naming

### ISSUE THREAD

**Issue by danepowell** [jenter/decoupled-drupal#2]
The repo is named decoupled-drupal but the Drush alias is drupaldecoupled. As is the enforced commit message prefix. And we don't yet have a standard for module/theme prefixes, but I've chosen `dd_` for now (e.g. `dd_content`).

We should probably harmonize these things. Ideally, the alias and commit message prefix would be quite a bit shorter than drupaldecoupled as well.

**Comment by jenter** [comment]
@danepowell do we still want to review this?

**Comment by danepowell** [comment]
Yes this still bothers me :)

Maybe we just use `decoupled` for everything?

So the alias would be `drush @decoupled.local uli`, and modules would be named like `decoupled_content`.

And I'd vote for just getting rid of the enforced message syntax (I can add a flag to disable it)

Let me know if that sounds good and I can take care of it.

**Comment by jenter** [comment]
@danepowell yeah makes sense, especially since we are going to use this same Drupal codebase for v2 with React. So the Drupal side should stay the same. Once you have made the changes let me know so I can update the tutorial
