### ISSUE TITLE
Permissions issue made it hard to create account on first local install.

### ISSUE THREAD

**Issue by gnarf** [jenter/decoupled-drupal#8]
After following the documentation I ran into an issue with permissions that was popping warnings up all over the front-end rendering that made it pretty hard to use the "create user" interface:

> Debug: Key file "file:///var/www/drupaldecoupled/keys/snakeoil_public.key" permissions are not correct, should be 600 or 660 instead of 644 in League\OAuth2\Server\CryptKey->__construct() (line 56 of /var/www/drupaldecoupled/vendor/league/oauth2-server/src/CryptKey.php).

`vagrant ssh -c "chmod 0600 /var/www/drupaldecoupled/keys/snakeoil_public.key"` was the fix, we could probably automate that as a part of the vagrant provisioning scripts

**Comment by CashWilliams** [comment]
It sounds like this is breaking builds in CI, thus needs to be fixed in the repo.

**Comment by gnarf** [comment]
https://github.com/gnarf/decoupled-drupal/commit/bfd5dcecc8c5c30c0d583e22f3f004a0b4b440c8
seemed to fix on CI, but wouldn't affect the vagrant I don't think

**Comment by CashWilliams** [comment]
#13 should fix this, but will leave open until confirmed.

**Comment by jenter** [comment]
merged, closing
